train:
  _target_: src.datasets.LibrispeechDataset
  part: "train_clean"
  instance_transforms: ${transforms.instance_transforms.train}
  data_dir: ${data_dir}
  index_dir: ${index_dir}
val:
  _target_: src.datasets.LibrispeechDataset
  part: "dev-clean"
  instance_transforms: ${transforms.instance_transforms.inference}
  data_dir: ${data_dir}
  index_dir: ${index_dir}
  limit: 10000
