dev_clean:
  _target_: src.datasets.LibrispeechDataset
  part: "dev-clean"
  instance_transforms: ${transforms.instance_transforms.inference}
  data_dir: ${data_dir}
  index_dir: ${index_dir}
dev_other:
  _target_: src.datasets.LibrispeechDataset
  part: "dev-other"
  instance_transforms: ${transforms.instance_transforms.inference}
  data_dir: ${data_dir}
  index_dir: ${index_dir}