train:
  _target_: src.datasets.LibrispeechDataset
  part: "test-clean"
  limit: 2
  instance_transforms: ${transforms.instance_transforms.train}
  data_dir: ${data_dir}
  index_dir: .
# we filter partitions in one batch test to check the pipeline
# do not filter test dataset, you want to evaluate on the whole dataset
val:
  _target_: src.datasets.LibrispeechDataset
  part: "test-clean"
  limit: 2
  instance_transforms: ${transforms.instance_transforms.inference}
  data_dir: ${data_dir}
  index_dir: .