train: [] # metrics that are calculated during training
inference: # metrics that are calculated during inference (eval)
  - _target_: src.metrics.CERMetric
    name: "CER_(Beam serach with beam_width=200 and LM Guidance)" # it is better to avoid spaces in names
  - _target_: src.metrics.WERMetric
    name: "WER_(Beam serach with beam_width=200 and LM Guidance)"
