train: [] # metrics that are calculated during training
inference: # metrics that are calculated during inference (eval)
  - _target_: asr_hw.src.metrics.CERMetric
    name: "CER_(Argmax)" # it is better to avoid spaces in names
  - _target_: asr_hw.src.metrics.WERMetric
    name: "WER_(Argmax)"
