train:
    get_spectrogram: # special key for getting spectrogram
      _target_: src.transforms.spec_augs.LogMelSpecTransform
      sample_rate: 16000
      n_fft: 512
      win_length: 400
      hop_length: 160
      n_mels: 80
      power: 2.0
      n_bands: ${transforms.batch_transforms.train.get_spectrogram.n_mels}
    audio:
      _target_: torch.nn.Sequential
      
    spectrogram:
      _target_: torch.nn.Sequential # to apply several transforms sequentially
      _args_:
        - _target_: src.transforms.spec_augs.CVMN

inference:
  get_spectrogram: ${transforms.batch_transforms.train.get_spectrogram}
  spectrogram: ${transforms.batch_transforms.train.spectrogram}