train:
    spectrogram:
      _target_: torch.nn.Sequential # to apply several transforms sequentially
      _args_:
        - _target_: src.transforms.spec_augs.CVMN

inference:
  spectrogram: ${transforms.batch_transforms.train.spectrogram}