train:
    spectrogram:
      _target_: torch.nn.Sequential # to apply several transforms sequentially
      _args_:
        - _target_: torchaudio.transforms.FrequencyMasking
          freq_mask_param: 20
        - _target_: torchaudio.transforms.FrequencyMasking
          freq_mask_param: 20
        - _target_: torchaudio.transforms.TimeMasking
          time_mask_param: 30
        - _target_: torchaudio.transforms.TimeMasking
          time_mask_param: 30
        - _target_: src.transforms.spec_augs.CVMN

inference:
  spectrogram:
    _target_: torch.nn.Sequential
    _args_:
      - _target_: src.transforms.spec_augs.CVMN