train:
    spectrogram:
      _target_: torch.nn.Sequential # to apply several transforms sequentially
      _args_:
        - _target_:  src.transforms.spec_augs.Permute
          permutation: [1, 2, 3, 0]
        - _target_: torchaudio.transforms.FrequencyMasking
          freq_mask_param: 15
        - _target_: torchaudio.transforms.FrequencyMasking
          freq_mask_param: 15

inference:
  spectrogram:
    _target_: torch.nn.Sequential
    _args_:
      - _target_: src.transforms.spec_augs.Permute
        permutation: [1, 2, 3, 0]
