tokenizer:
  _target_: asr_hw.src.tokenizer.BPETokenizer
  model_path: ${tokenizer_config.save_path}/bpe_tokenizer.json

tokenizer_trainer:
  _target_: asr_hw.src.tokenizer.BPETokenizer.train
  data_dir: ${data_dir}
  init_vocab_path: ${tokenizer_config.init_vocab_path}
  save_path: ${tokenizer_config.save_path}/bpe_tokenizer.json
  max_token_length: 3
  vocab_size: 90
  