train:
  get_spectrogram: # special key for getting spectrogram
    _target_: src.transforms.spec_augs.LogMelSpecTransform
    sample_rate: 16000
    n_fft: 512
    win_length: 400
    hop_length: 160
    n_mels: 80
    top_db: 80
    power: 2.0
  spectrogram:
    _target_: torchvision.transforms.v2.Compose
    transforms:
      - _target_: src.transforms.spec_augs.CVMN
      - _target_: src.transforms.spec_augs.Permute
        permutation: [2, 0, 1]

inference:
  get_spectrogram: ${transforms.instance_transforms.train.get_spectrogram}
  spectrogram: ${transforms.instance_transforms.train.spectrogram}