train:
  get_spectrogram: # special key for getting spectrogram
    _target_: src.transforms.spec_augs.LogSpecTransform
    n_fft: 320
    win_length: 320
    hop_length: 160
    top_db: 80
    power: 2.0
  spectrogram:
    _target_: torchvision.transforms.v2.Compose
    transforms:
      - _target_: src.transforms.spec_augs.Permute
        permutation: [2, 0, 1]

inference:
  get_spectrogram: ${transforms.instance_transforms.train.get_spectrogram}
  spectrogram: ${transforms.instance_transforms.train.spectrogram}