train:
  get_spectrogram: # special key for getting spectrogram
    _target_: asr_hw.src.transforms.spec_augs.LogMelSpecTransform
    sample_rate: 16000
    n_fft: 512
    win_length: 400
    hop_length: 160
    n_mels: 80
    power: 2.0
    n_bands: ${transforms.instance_transforms.train.get_spectrogram.n_mels}
  audio:
    _target_: torch_audiomentations.Compose
    transforms:
      - _target_: asr_hw.src.transforms.wav_augs.Gain
        min_gain_in_db: -6
        max_gain_in_db: 6
        p: 1.0
        sample_rate: 16000
        output_type: tensor
      - _target_: asr_hw.src.transforms.wav_augs.ImpulseResponse
        ir_paths: ${aug_dir}/rir
        convolve_mode: full
        mode: per_example
        sample_rate: 16000
        output_type: tensor
        p: 0.4
        compensate_for_propagation_delay: False
      - _target_: asr_hw.src.transforms.wav_augs.BackgroundNoise
        background_paths: ${aug_dir}/noise
        min_snr_in_db: 10
        max_snr_in_db: 20
        mode: per_example
        p: 0.4
        sample_rate: 16000
        output_type: tensor
      - _target_: asr_hw.src.transforms.wav_augs.PeakNorm

inference:
  get_spectrogram: ${transforms.instance_transforms.train.get_spectrogram}
  audio:
    _target_: torch_audiomentations.Compose
    transforms:
      - _target_: asr_hw.src.transforms.wav_augs.PeakNorm
